name: PR
env:
  TEST: v2.1.1

on:
  pull_request:
    branches:
    - main

jobs:
  deploy-dev:
    name: Deploy to DEV
    environment: dev_environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: LouisBrunner/checks-action@v1.1.1
        id: integration-tests
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Integration tests
          status: in_progress

      # - uses: LouisBrunner/checks-action@v1.1.1
      #   if: env.status == 'success'
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     check_id: ${{ steps.integration-tests.outputs.check_id }}
      #     conclusion: success

      - uses: LouisBrunner/checks-action@v1.1.1
        # if: env.status == 'failure'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check_id: ${{ steps.integration-tests.outputs.check_id }}
          conclusion: failure
          output: |
            {"summary": "OK, er ging iets mis"}
